### ISSUE TITLE
Not reserving emails getting error, but still shows up in icloud dashboard

### ISSUE THREAD

**Issue by Ronanpatel1** [rtunazzz/hidemyemail-generator#12]
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000000034AB130>
Traceback (most recent call last):
  File "C:\Users\Roni\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Users\Roni\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Users\Roni\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
  File "C:\Users\Roni\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed

And what is the purpose of reserving the emails?

**Comment by Ronanpatel1** [comment]
nvm im dumb, i can only gen 13 per 30 minutes

**Comment by rtunazzz** [comment]
Glad you got it sorted out @Ronanpatel1!

Seems like this definitely should be handled better. I'll have a look when I'm free but feel free to open a PR if you'd like 🙂

To respond your question about reserving the emails - that's just the process of how Apple has it set up. First they generate the email for you, then you have to reserve it
