### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by abensim** [rtunazzz/hidemyemail-generator#14]
i have this when using main exec from MAC zip 

How many iCloud emails you want to generate?: 3
[17:34:42] Generating 3 email(s)...                                   main.py:94
────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "aiohttp/connector.py", line 986, in _wrap_create_connection
  File "asyncio/base_events.py", line 1097, in create_connection
  File "asyncio/base_events.py", line 1127, in _create_connection_transport
  File "asyncio/sslproto.py", line 534, in data_received
  File "asyncio/sslproto.py", line 188, in feed_ssldata
  File "ssl.py", line 975, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 185, in <module>
    loop.run_until_complete(generate())
  File "asyncio/base_events.py", line 649, in run_until_complete
  File "main.py", line 174, in generate
    await hme.generate()
  File "main.py", line 99, in generate
    batch = await self._generate(
  File "main.py", line 82, in _generate
    return filter(lambda e: e is not None, await asyncio.gather(*tasks))
  File "main.py", line 37, in _generate_one
    gen_res = await self.generate_email()
  File "icloud/hidemyemail.py", line 65, in generate_email
    async with self.s.post(
  File "aiohttp/client.py", line 1138, in __aenter__
  File "aiohttp/client.py", line 535, in _request
  File "aiohttp/connector.py", line 542, in connect
  File "aiohttp/connector.py", line 907, in _create_connection
  File "aiohttp/connector.py", line 1206, in _create_direct_connection
  File "aiohttp/connector.py", line 1175, in _create_direct_connection
  File "aiohttp/connector.py", line 988, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host p68-maildomainws.icloud.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]
[97036] Failed to execute script 'main' due to unhandled exception!

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by rtunazzz** [comment]
For whatever reason, the app/Python can't validate any SSL connections. You can try running:
```
/Applications/Python\ 3.10/Install\ Certificates.command
```
_(replace 3.10 with whatever version of Python you have)_


Attaching a StackOverflow thread here which seemed helpful:
> https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error

---

I'll add a small SSL addition which might help but no promises.

**Comment by rtunazzz** [comment]
@abensim you can try the `main` branch now and see if that helps, let me know!
