### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gdszps** [rtunazzz/hidemyemail-generator#4]
Traceback (most recent call last):
  File "/Users/wxx/PycharmProjects/GetCookies/hidemyemail-generator/main.py", line 165, in <module>
    loop.run_until_complete(generate())
  File "/Users/wxx/opt/anaconda3/envs/GetCookies/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/wxx/PycharmProjects/GetCookies/hidemyemail-generator/main.py", line 157, in generate
    await i.generate()
  File "/Users/wxx/PycharmProjects/GetCookies/hidemyemail-generator/main.py", line 96, in generate
    batch = await self._generate(count if count < MAX_CONCURRENT_TASKS else MAX_CONCURRENT_TASKS)
  File "/Users/wxx/PycharmProjects/GetCookies/hidemyemail-generator/main.py", line 81, in _generate
    return filter(lambda e: e is not None, await asyncio.gather(*tasks))
  File "/Users/wxx/PycharmProjects/GetCookies/hidemyemail-generator/main.py", line 38, in _generate_one
    gen_res = await self.generate_email()
  File "/Users/wxx/PycharmProjects/GetCookies/hidemyemail-generator/icloud/hidemyemail.py", line 66, in generate_email
    res = await resp.json(content_type='text/html')
  File "/Users/wxx/opt/anaconda3/envs/GetCookies/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1103, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: application/json; charset=utf-8', url=URL('https://p68-maildomainws.icloud.com/v1/hme/generate?clientBuildNumber=2206Hotfix11&clientMasteringNumber=2206Hotfix11&clientId=&dsid=')

**Comment by gdszps** [comment]
────────────────────────────────────────────────────────────────────────────────
How many iCloud emails you want to generate?: 10
[14:54:55] Generating 10 email(s)...                                  main.py:91
────────────────────────────────────────────────────────────────────────────────
           [ERR] - Failed to generate email. Reason: Private email    main.py:49
           feature is not eligible for this person                              
[14:54:56] [ERR] - Failed to generate email. Reason: Private email    main.py:49
           feature is not eligible for this person                              
           [ERR] - Failed to generate email. Reason: Private email    main.py:49
           feature is not eligible for this person                              
           [ERR] - Failed to generate email. Reason: Private email    main.py:49
           feature is not eligible for this person                              
           [ERR] - Failed to generate email. Reason: Private email    main.py:49
           feature is not eligible for this person                              
           [ERR] - Failed to generate email. Reason: Private email    main.py:49
           feature is not eligible for this person                              
           [ERR] - Failed to generate email. Reason: Private email    main.py:49
           feature is not eligible for this person                              
[14:54:57] [ERR] - Failed to generate email. Reason: Private email    main.py:49
           feature is not eligible for this person                              
[14:55:05] [ERR] - Failed to generate email. Reason: Request timed    main.py:49
           out                                                                  
           [ERR] - Failed to generate email. Reason: Request timed    main.py:49
           out
